apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: viennacalling-backend
  name: viennacalling-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: viennacalling-backend
  template:
    metadata:
      labels:
        app: viennacalling-backend
    spec:
      containers:
        - image: jajcoszek/viennacalling-backend:1.0.0
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 1Gi
