apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: jajcoszek/viennacalling-backend:1.0.0
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
