apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: jajcoszek/viennacalling-backend
  newName: jajcoszek/viennacalling-backend
  newTag: 1.2.0
