apiVersion: v1
kind: Service
metadata:
  name: viennacalling-backend
spec:
  type: ClusterIP
  selector:
    app: viennacalling-backend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
